### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [CohesionForce/avro-toolkit#10]
Hello Avro-Toolkit team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the Avro-Toolkit project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by jperiodlangley** [comment]
Hi @miklossy,

I wasn't sure if I should comment on this issue, or the corresponding GitHub issue mentioned above. I may have done this backward for the [HLA Toolkit](https://github.com/CohesionForce/hla-toolkit) - if so, sorry about that.

We appreciate everything that Itemis does for the Xtext community!

**Comment by jperiodlangley** [comment]
<tr>
	<td><a href="https://github.com/CohesionForce/avro-toolkit">Avro Toolkit</a></td>
	<td>Framework for building Apache Avro schemas and converters from an EMF model.</td>
	<td>EPL 2.0</td>
	<td>Framework</td>
	<td>CohesionForce, Inc</td>
</tr>

**Comment by miklossy** [comment]
> We appreciate everything that Itemis does for the Xtext community!

Thanks!

**Comment by miklossy** [comment]
The `Avro Toolkit` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
